package idp

import (
	"fmt"
	"strconv"
	"strings"

	"golang.org/x/crypto/bcrypt"
)

// User is one account inside a client's entry in the clients file. Passwords
// are stored as bcrypt hashes — the per-user salt is part of the bcrypt
// format ($2a$10$<salt><hash>), so no separate salt field is needed. Roles,
// when set, are released as the roles claim on every token of the user.
type User struct {
	Username     string   `json:"username"`
	PasswordHash string   `json:"password_hash"`
	Email        string   `json:"email,omitempty"`
	Name         string   `json:"name,omitempty"`
	Roles        []string `json:"roles,omitempty"`
}

// UserStore is the account backend of a single registered client. It is an
// interface so the clients-file backend shipped here can later be swapped for
// a database or an external identity source without touching the IdP core.
type UserStore interface {
	// Lookup returns the account with the given username.
	Lookup(username string) (User, bool)
	// Count returns the number of accounts (for startup logging).
	Count() int
	// DummyHash is a verifiable bcrypt hash burned on unknown-user lookups
	// so response timing does not reveal which usernames exist. Its cost
	// should match the cost of the stored user hashes.
	DummyHash() string
}

// validate checks one user entry when the clients file is loaded or saved.
func (u User) validate() error {
	if strings.TrimSpace(u.Username) == "" {
		return fmt.Errorf("username must not be empty")
	}
	if u.Username != strings.TrimSpace(u.Username) {
		return fmt.Errorf("username %q must not have leading or trailing whitespace", u.Username)
	}
	if !isBcryptHash(u.PasswordHash) {
		return fmt.Errorf("user %q: password_hash must be a 60-character bcrypt hash "+
			"like $2a$10$... (generate one with: clientctl hash)", u.Username)
	}
	seenRoles := make(map[string]bool, len(u.Roles))
	for _, role := range u.Roles {
		if strings.TrimSpace(role) == "" {
			return fmt.Errorf("user %q: roles must not contain empty entries", u.Username)
		}
		if role != strings.TrimSpace(role) {
			return fmt.Errorf("user %q: role %q must not have leading or trailing whitespace", u.Username, role)
		}
		if seenRoles[role] {
			return fmt.Errorf("user %q: duplicate role %q", u.Username, role)
		}
		seenRoles[role] = true
	}
	return nil
}

// validateUserSlice rejects duplicate usernames and entries that fail the
// user validation. Called for every client's users array.
func validateUserSlice(users []User) error {
	seen := make(map[string]bool, len(users))
	for i, u := range users {
		if err := u.validate(); err != nil {
			return fmt.Errorf("user entry %d: %w", i, err)
		}
		if seen[u.Username] {
			return fmt.Errorf("duplicate username %q", u.Username)
		}
		seen[u.Username] = true
	}
	return nil
}

// isBcryptHash reports whether s looks like a modular bcrypt hash.
func isBcryptHash(s string) bool {
	return len(s) == 60 &&
		(strings.HasPrefix(s, "$2a$") || strings.HasPrefix(s, "$2b$") || strings.HasPrefix(s, "$2y$"))
}

// newDummyHash creates the hash burned on failed lookups so an attacker
// cannot probe for valid usernames via response timing: comparing against a
// real hash takes as long as the configured bcrypt cost, a missing user would
// otherwise return instantly.
func newDummyHash(cost int) string {
	h, err := bcrypt.GenerateFromPassword([]byte("minidp-timing-equalizer-dummy"), cost)
	if err != nil {
		// Cannot happen for a fixed plaintext and valid cost; fail loudly.
		panic(fmt.Sprintf("generate timing-equalisation dummy hash: %v", err))
	}
	return string(h)
}

// bcryptCostOf extracts the cost factor from a modular bcrypt hash
// ("$2a$10$..."). It falls back to bcrypt.DefaultCost for malformed input.
func bcryptCostOf(hash string) int {
	if len(hash) < 7 || hash[0] != '$' {
		return bcrypt.DefaultCost
	}
	cost, err := strconv.Atoi(hash[4:6])
	if err != nil || cost < bcrypt.MinCost || cost > bcrypt.MaxCost {
		return bcrypt.DefaultCost
	}
	return cost
}

// HashPassword derives a salted bcrypt hash for a user entry. The salt is
// generated by bcrypt and embedded in the returned hash string. Shared with
// the clientctl tool.
func HashPassword(password string, cost int) (string, error) {
	if cost < bcrypt.MinCost || cost > bcrypt.MaxCost {
		return "", fmt.Errorf("bcrypt cost must be between %d and %d", bcrypt.MinCost, bcrypt.MaxCost)
	}
	h, err := bcrypt.GenerateFromPassword([]byte(password), cost)
	if err != nil {
		return "", err
	}
	return string(h), nil
}

// verifyHash wraps bcrypt comparison for readability.
func verifyHash(hash, password string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}
